language: rust
rust:
  - nightly


env:
  global:
    - LD_LIBRARY_PATH=${HOME}/wayland/lib
    - LIBRARY_PATH=${HOME}/wayland/lib
    - CPATH=${HOME}/wayland/include
    - XDG_RUNTIME_DIR=/tmp

before_install:
  - wget http://wayland.freedesktop.org/releases/wayland-1.7.0.tar.xz
  - tar xJf wayland-1.7.0.tar.xz
  - pushd wayland-1.7.0
  - ./configure --disable-documentation --prefix=${HOME}/wayland
  - make
  - make install
  - popd
